### ISSUE TITLE
Problem with grep

### ISSUE THREAD

**Issue by mgutierrezp** [kernelOfTruth/pulseaudio-equalizer#3]
Please force grep to use the --color=never parameter. Otherwise, some system values are not read properly (default sink, etc). I have for example some grep parameter by default when grep is executed. This was a headache to realize the problem

**Comment by kernelOfTruth** [comment]
@mgutierrezp this should be addressed by version 4.0 , the involuntary volume raise is also addressed,

thanks to @kabili207
